// components/EventAgentWidget.tsx
"use client";

import { useState, useRef, useEffect } from 'react';
import { Send, Loader2, Sparkles, X, CheckCircle2 } from 'lucide-react';
import { useEvents } from '@/hooks/useFirebase';
import { usePaymentPlans } from '@/hooks/usePaymentPlans';
import toast from 'react-hot-toast';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
}

const GREETING =
  "Hi! Tell me about the event you'd like to create — name, type, date, time, venue, and who's hosting. I'll ask for anything that's missing, then create it for you.";

export default function EventAgentWidget() {
  const { createEvent } = useEvents();
  const { canCreateEvent, incrementEventCount, refreshPlan } = usePaymentPlans();

  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    { id: 'greeting', role: 'assistant', text: GREETING },
  ]);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [created, setCreated] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages, open]);

  const resetChat = () => {
    setMessages([{ id: 'greeting', role: 'assistant', text: GREETING }]);
    setCreated(false);
    setInput('');
  };

  const handleSend = async () => {
    const text = input.trim();
    if (!text || sending || created) return;

    if (!canCreateEvent()) {
      toast.error('You have reached your event limit. Please upgrade your plan.');
      return;
    }

    const userMsg: ChatMessage = { id: `u-${Date.now()}`, role: 'user', text };
    const nextMessages = [...messages, userMsg];
    setMessages(nextMessages);
    setInput('');
    setSending(true);

    try {
      // Drop the initial greeting — it's UI-only and was never actually
      // generated by the model, so including it would make the first item
      // in the API's message history an 'assistant' turn, which Gemini
      // rejects (it requires the first turn to be 'user').
      const apiMessages = nextMessages
        .filter((m) => m.id !== 'greeting')
        .map((m) => ({
          role: m.role,
          content: m.text,
        }));

      const res = await fetch('/api/event-agent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: apiMessages }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Something went wrong');
      }

      if (data.type === 'ready') {
        const eventData = data.eventData;
        const functionsArray = eventData.eventType === 'Wedding' && Array.isArray(eventData.functions)
          ? eventData.functions
          : [];

        const eventId = await createEvent({
          eventName: eventData.eventName,
          eventType: eventData.eventType,
          eventDate: eventData.eventDate,
          venue: eventData.venue,
          address: eventData.address,
          hostNames: eventData.hostNames,
          coupleNames: eventData.coupleNames || '',
          description: eventData.description || '',
          themeColor: '#3B82F6',
          googleMaps: '',
          imageUrl: '',
          functions: functionsArray,
        });

        if (!eventId) throw new Error('Failed to create event');

        await incrementEventCount();
        await refreshPlan();

        setCreated(true);
        setMessages((prev) => [
          ...prev,
          {
            id: `b-${Date.now()}`,
            role: 'assistant',
            text: `Done! I've created "${eventData.eventName}". You can view and edit it from the Events page.`,
          },
        ]);
        toast.success('Event created!');
      } else {
        setMessages((prev) => [
          ...prev,
          { id: `b-${Date.now()}`, role: 'assistant', text: data.text },
        ]);
      }
    } catch (err: any) {
      console.error('AI event creation error:', err);
      toast.error(err.message || 'Something went wrong');
      setMessages((prev) => [
        ...prev,
        {
          id: `b-${Date.now()}`,
          role: 'assistant',
          text: "Sorry, something went wrong on my end. Could you try again?",
        },
      ]);
    } finally {
      setSending(false);
    }
  };

  return (
    <>
      {/* Floating launcher — stacked above the SupportChatbot ("Chat with
          us" at bottom-24) and the page's own "Help & Support" button
          (bottom-6), so all three sit one above another without
          overlapping. */}
      {!open && (
        <button
          type="button"
          onClick={() => setOpen(true)}
          aria-label="Create event with AI"
          className="fixed bottom-40 right-6 z-50 flex items-center gap-2 rounded-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-3 shadow-lg transition-colors"
        >
          <Sparkles className="h-5 w-5" />
          <span className="text-sm font-medium hidden sm:inline">Create with AI</span>
        </button>
      )}

      {open && (
        <div className="fixed bottom-6 right-6 z-50 w-[90vw] max-w-sm h-[70vh] max-h-[560px] bg-white dark:bg-gray-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-gray-700 flex flex-col overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 bg-purple-600 text-white shrink-0">
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5" />
              <span className="font-medium text-sm">Create Event with AI</span>
            </div>
            <div className="flex items-center gap-1">
              {created && (
                <button
                  type="button"
                  onClick={resetChat}
                  className="text-xs hover:bg-white/20 rounded-full px-2 py-1 transition-colors"
                >
                  New
                </button>
              )}
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close"
                className="hover:bg-white/20 rounded-full p-1 transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          <div ref={scrollRef} className="flex-1 overflow-y-auto px-3 py-3 space-y-2">
            {messages.map((m) => (
              <div
                key={m.id}
                className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-[85%] rounded-2xl px-3 py-2 text-sm ${
                    m.role === 'user'
                      ? 'bg-purple-600 text-white rounded-br-sm'
                      : 'bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-100 rounded-bl-sm'
                  }`}
                >
                  {m.text}
                </div>
              </div>
            ))}

            {sending && (
              <div className="flex justify-start">
                <div className="bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-bl-sm px-3 py-2">
                  <Loader2 className="h-4 w-4 animate-spin text-gray-500" />
                </div>
              </div>
            )}

            {created && (
              <div className="flex justify-center pt-1">
                <span className="flex items-center gap-1.5 text-xs font-medium text-green-700 bg-green-50 dark:bg-green-900/20 dark:text-green-400 px-3 py-1.5 rounded-full">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Event created
                </span>
              </div>
            )}
          </div>

          <div className="border-t border-gray-200 dark:border-gray-700 p-2 shrink-0">
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                placeholder={created ? "Tap 'New' to create another" : 'Describe your event...'}
                disabled={sending || created}
                className="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-purple-500 disabled:opacity-60"
              />
              <button
                type="button"
                onClick={handleSend}
                disabled={sending || !input.trim() || created}
                aria-label="Send"
                className="p-2 rounded-lg bg-purple-600 text-white hover:bg-purple-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                <Send className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}